Allowed for cases when x and y bias per image values are missing
Prior to this commit, running the TUI on an unaligned project gave:

  Traceback (most recent call last):
    File "pyswift_tui.py", line 881, in <module>
      num_layers=num_layers )
    File "pyswift_tui.py", line 472, in run_json_project
      x_bias = atrm['method_data']['bias_x_per_image']
  KeyError: 'bias_x_per_image'