Added larger stack option (and experiments) for compiling in Windows
It turns out that "mir" has been segment faulting for some time in
Windows. Further investigation revealed a "mir.exe.stackdump" file
containing:

  Exception: STATUS_STACK_OVERFLOW at rip=00100406836
  rax=00000000001DE7D8 rbx=0000000000000004 rcx=00000000FFE03058
  rdx=00000001004107A0 rsi=0000000000000004 rdi=00000001004107A0
  r8 =00000000FFFFC06C r9 =0000000000000004 r10=0000000100000000
  r11=0000000100409B57 r12=00000000FFFFC150 r13=00000000FFFFC350
  r14=00000000FFFFC550 r15=0000000000000004
  rbp=0000000100537388 rsp=00000000FFFFC040
  program=C:\cygwin64\..\source\mir.exe, pid 3015,
  thread
  cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
  Stack trace:
  Frame        Function    Args
  00100537388  00100406836 (00100404C56, 00000000004, 00000000004, 001004107A0)
  00100537388  000003D67D8 (00000000004, 00000000004, 001004107A0, 00100537388)
  00100537388  00000000004 (00000000004, 001004107A0, 00100537388, 000FFFFC150)
  00100537388  00100404C56 (000FFFFC150, 408C380000000000, 00180150820, 4008000000000000)
  00100537388  00100409B78 (00000000020, 30001000000FF00, 0018004A7AA, 001800497F0)
  000FFFFCCD0  0018004A816 (00000000000, 00000000000, 00000000000, 00000000000)
  00000000000  00180048353 (00000000000, 00000000000, 00000000000, 00000000000)
  000FFFFFFF0  00180048404 (00000000000, 00000000000, 00000000000, 00000000000)
  End of stack trace

This led to a series of stack size experiments:

  These failed in Windows 10:

    -Wl,--stack,0x100000
    -Wl,--stack,0x200000

  These worked in Windows 10:

    -Wl,--stack,0x400000
    -Wl,--stack,0x800000
    -Wl,--stack,0x1000000
    -Wl,--stack,0x10000000

This version implements 0x1000000 as a reasonably safe size.